// packages/mfe-rick-morty/src/App.vue
<script setup>
import HelloWorld from './components/HelloWorld.vue'
</script>

<template>
    <nav class="bg-gray-800 text-white p-4">
    <a href="/shell" class="text-blue-500 hover:underline focus:underline focus:outline-none">Marvel</a>
    <span class="mx-2 text-gray-400">|</span>
    <a href="/shell/one-pice" class="text-blue-500 hover:underline focus:underline focus:outline-none">One Piece</a>
    <span class="mx-2 text-gray-400">|</span>
    <a href="/edge/pokemon" class="text-yellow-500 hover:underline focus:underline focus:outline-none">edge pokemon</a>
    <span class="mx-2 text-gray-400">|</span>
    <a href="/edge/rick-morty" class="text-yellow-500 hover:underline focus:underline focus:outline-none">edge rick-morty</a>
    <span class="mx-2 text-gray-400">|</span>
    <a href="/edge/vanilla" class="text-yellow-500 hover:underline focus:underline focus:outline-none">edge vanilla</a>
  </nav>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// packages/mfe-pokemon/src/App.tsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <nav className="bg-gray-800 text-white p-4">
        <a href="/shell"className="text-blue-500 hover:underline focus:underline focus:outline-none">Marvel</a>
        <span className="mx-2 text-gray-400">|</span>
        <a href="/shell/one-pice"className="text-blue-500 hover:underline focus:underline focus:outline-none">One Piece</a>
        <span className="mx-2 text-gray-400">|</span>
        <a href="/edge/pokemon" className="text-yellow-500 hover:underline focus:underline focus:outline-none">edge pokemon</a>
        <span className="mx-2 text-gray-400">|</span>
        <a href="/edge/rick-morty" className="text-yellow-500 hover:underline focus:underline focus:outline-none">edge rick-morty</a>
        <span className="mx-2 text-gray-400">|</span>
        <a href="/edge/vanilla" className="text-yellow-500 hover:underline focus:underline focus:outline-none">edge vanilla</a>
      </nav>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}

export default App
